version: '3.6'
services:
  vault:
    image: vault:1.13.3
    container_name: vault
    restart: on-failure:10
    ports:
      - '8200:8200'
    environment:
      VAULT_ADDR: 'http://localhost:8200'
      VAULT_CLUSTER_ADDR: 'http://vault-prod:8201'
      VAULT_API_ADDR: 'http://vault-prod:8200'
      VAULT_RAFT_NODE_ID: 'vault-prod'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/vault/data
      - ./config:/vault/config
    healthcheck:
      retries: 5
    networks:
      - vault-prod
    entrypoint: vault server -config=/vault/config/vault-config.hcl

networks:
  vault-prod:
